server:
  port: 7777


# swagger配置
springfox:
  documentation:
    swagger-ui:
      enabled: true
    swagger:
      v2:
        enabled: true
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

